
services:
    database:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_DB=mangawelt
            - POSTGRES_USER=admin        # Username for your postgres datbase
            - POSTGRES_PASSWORD=klnFe5oVOI1c6dn3Aub6hkBeI    # Password for your postgres user
        ports:
            - '5432:5432'
        volumes:
            - ./database:/var/lib/postgresql
        hostname: postgresql
        networks:
            - app
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - app
    backend:
        stdin_open: true
        build:
            context: "backend"
            dockerfile: Dockerfile
        restart: always
        ports:
            - '0.0.0.0:8000:8000'
        volumes:
            - ./backend:/app
        environment:
            - DEBUG=True
        hostname: backend
        networks:
            - app
        env_file: ".env"
        depends_on:
            - database
    frontend:
        stdin_open: true
        build:
            context: "frontend"
            dockerfile: Dockerfile.dev
        ports:
            - '5173:5173'
        volumes:
            - ./frontend/:/app
            - /app/node_modules
        restart: always
        tty: true
        environment:
            - FRONTEND_PORT=5173
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true
        networks:
            - app

networks:
    app:
        driver: bridge